## 服务端口配置
#server:
#  port: 7002
## Spring应用基础配置
#spring:
#  application:
#    name: order # 服务名称（需唯一）
## Eureka客户端配置（服务发现）
#eureka:
#  client:
#    service-url:
#      # defaultZone: http://localhost:8000/eureka # Eureka注册中心地址
#      defaultZone: http://server1:6001/eureka/,http://server2:6002/eureka/,http://server3:6003/eureka/
#    instance:
#      lease-renewal-interval-in-seconds: 30 # 心跳间隔时间
#      lease-expiration-duration-in-seconds: 90 # 心跳超时时间，超过这个时间，Eureka会从注册中心中移除这个服务
#      prefer-ip-address: true # ✅ 强烈建议开启