# user的application.yml配置文件
# 服务端口配置
server:
  port: 7003 # 服务名称（需唯一）

# Spring应用基础配置
spring:
  application:
    name: user

# Eureka客户端配置（服务发现）
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka # Eureka注册中心地址
  instance:
    instance-id: ${spring.application.name}:${server.port} # 实例ID唯一（避免IP变化导致重复）
    lease-renewal-interval-in-seconds: 30 # 心跳间隔时间
    lease-expiration-duration-in-seconds: 90 # 心跳超时时间，超过这个时间，Eureka会从注册中心中移除这个服务
    prefer-ip-address: true # ✅ 强烈建议开启。Eureka 客户端直接使用IP地址注册，而不是主机名。